sudo: required

language: bash

services:
  - docker

env:
  global:
    - DOCKER_IMAGE=emergya/ubuntu_16.04-wordpress
    - GIT_URL=git@github.com:sfbenitez/ubuntu_16.04-wordpress.git

script:
  - docker build -t $DOCKER_IMAGE .

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      DOCKER_IMAGE_COMMIT=$(git log -1 --pretty=format:'%h');
      DOCKER_IMAGE_TIMESTAMP=$(docker inspect -f '{{ .Created }}' ${DOCKER_IMAGE}|awk -F':' '{print $1$2}'|sed 's%-\|T%%g');
      docker tag $DOCKER_IMAGE:latest $DOCKER_IMAGE:$DOCKER_IMAGE_TIMESTAMP-$DOCKER_IMAGE_COMMIT;
      docker push $DOCKER_IMAGE:latest;
      docker push $DOCKER_IMAGE:$DOCKER_IMAGE_TIMESTAMP-$DOCKER_IMAGE_COMMIT;
      curl -ILk 'https://'"${JENKINS_USER}"':'"${JENKINS_API_TOKEN}"'@jenkins.emergya.com/job/'"${JENKINS_JOB_NAME}"'/buildWithParameters?token='"${JENKINS_JOB_TOKEN}"'&GIT_URL='"${GIT_URL}"'&DOCKER_IMAGE='"${DOCKER_IMAGE}";
    fi

notifications:
  email:
    recipients:
      - sferrete@emergya.com
    on_success: always
    on_failure: always
    
